## Numpy

### 1. Numpy Array and Operation

- numpy의 기본적인 사용법에 대해서 배워봅니다.


- numpy에서 numpy.array를 만드는 여러가지 방법과 지원하는 연산자에 대해서 공부합니다.

### 1.1. Numpy Array creation

In [ ]:
# numpy 라이브러리를 불러옵니다.
import numpy as np

In [ ]:
# 파이썬 리스트 선언
data = [1, 2, 3, 4, 5]
data

[1, 2, 3, 4, 5]

In [ ]:
# 파이썬 2차원 리스트(행렬) 선언
data2 = [[1,2],[3,4]]
data2

[[1, 2], [3, 4]]

In [ ]:
# 파이썬 list를 numpy array로 변환합니다.
arr = np.array(data)
# numpy array를 만드는 방식의 대부분은 파이썬 리스트를 np.array로 변환하는 방식입니다.
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
# 2차원 리스트를 np.array로 만듭니다.
arr2 = np.array(data2) # data2라는 리스트를 numpy array로 만들어라.
arr2 #2차원 numpy array -> 행렬!

array([[1, 2],
       [3, 4]])

In [ ]:
# 0부터 9까지 숫자를 자동으로 생성한 array
np.array(list(range((10))))
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 10부터 99까지 숫자를 자동으로 생성한 array
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [ ]:
arr.shape
arr2.shape

(2, 2)

### 1.2. Reshaping array

In [ ]:
# 3 x 3 행렬을 만들어봅시다.
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# reshape을 이용하여 만들어봅시다.
y = np.arange(1,10).reshape(3,3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# row vector를 column vector로
np.arange(6).reshape(6,1) # (6, ) != (6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
# 펼치기
x.reshape(-1,)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1.3. Concatenation of arrays

In [ ]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])
# arr1 + arr2 = ?
arr1 + arr2
# arr1와 arr2를 합칩니다
np.concatenate([arr1, arr2], axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# stacking vertically
np.vstack([arr1,arr2])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# stacking horizontally
np.hstack([arr1,arr2])

array([1, 2, 3, 4, 5, 6])

## 1.4. Array Arithmetic (like vector) --> Universal Function

In [ ]:
# v1 = (1, 2, 3), v2 = (4, 5, 6) 벡터 2개 생성하기.
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [ ]:
# 리스트로 더하기 연산해보기
L1 = [1,2,3]
L2 = [4,5,6]
L1 + L2

[1, 2, 3, 4, 5, 6]

In [ ]:
#  vector addition
v1 + v2

array([5, 7, 9])

In [ ]:
#  vector subtraction
v1 - v2

array([-3, -3, -3])

In [ ]:
# (not vector operation) elementwise multiplication
v1 * v2

array([ 4, 10, 18])

In [ ]:
# (not vector operation) elementwise division
v1 / v2

array([0.25, 0.4 , 0.5 ])

In [ ]:
# dot product
v1 @ v2 # 1x4 + 2x5 + 3x6 (내적)

32

### 1.5. Broadcast and Universal Function

- 서로 크기가 다른 numpy array를 연산할 때, 자동으로 연산을 전파(broadcast)해주는 기능. 행렬곱 연산을 할 때 편리하다.

In [ ]:
arr1 = np.array([1,2,3])

In [ ]:
arr2 = np.array([[-1, -1, -1],
                 [ 1,  1,  1]])
arr2.shape

(2, 3)

In [ ]:
# 2개의 array를 더해보면?
arr1 + arr2 # 2->2->3(v)

array([[0, 1, 2],
       [2, 3, 4]])

In [ ]:
# 2개의 array를 곱해보면? (**)
arr1 * arr2

array([[-1, -2, -3],
       [ 1,  2,  3]])

- Universal Function : broadcast 기능을 확장해서, numpy array의 모든 원소에 동일한 함수를 반복문으로 적용한 것과 같은 효과를 내는 기능.

In [ ]:
f = lambda x : 1/x

arr1 = np.array([1.,2.,3.])

for i in range(arr1.shape[0]):
  arr1[i] = f(arr1[i])

print(arr1)
arr1 = np.array([1.,2.,3.])
print(1 / arr1)

[1.         0.5        0.33333333]
[1.         0.5        0.33333333]


In [ ]:
# f = lambda x : x + 2
arr1 = arr1 * 3
arr1

array([3., 6., 9.])

### 1.6. Indexing


In [ ]:
arr1 = np.arange(10)

In [ ]:
# 첫번째 원소
arr1[0]

0

In [ ]:
# 마지막 원소
arr1[-1]

9

In [ ]:
# 앞에서부터 원소 3개 slicing
arr1[:3]

array([0, 1, 2])

In [ ]:
arr2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr2.shape

(3, 4)

In [ ]:
# arr2의 2row, 3column 원소 = 7
arr2[1,2]

7

In [ ]:
# arr2의 세번째 column [3, 7, 11]
arr2[:,2]

array([ 3,  7, 11])

In [ ]:
# arr2의 두번째 row
arr2[0:2,0:2]

array([[1, 2],
       [5, 6]])

## 2. Numpy Methods

- numpy에서 사용되는 여러가지 함수들을 사용해봅시다.

### 2.1. Math Functions 

In [ ]:
# 표준정규분포에서 random sampling을 한 원소를 가지는 5x3 행렬을 만든다.
mat1 = np.random.randn(5,3)
mat1

array([[-0.06663455,  2.41270643,  0.32438574],
       [ 0.00613605, -0.59051163, -0.43487646],
       [ 1.77747609, -0.31104668, -1.29997559],
       [-0.21019321, -0.40751532,  0.13845742],
       [ 0.74584362, -2.0368784 ,  1.94915196]])

In [ ]:
# mat1에 절대값 씌우기
np.abs(mat1)

array([[0.06663455, 2.41270643, 0.32438574],
       [0.00613605, 0.59051163, 0.43487646],
       [1.77747609, 0.31104668, 1.29997559],
       [0.21019321, 0.40751532, 0.13845742],
       [0.74584362, 2.0368784 , 1.94915196]])

In [ ]:
# mat1 제곱하기
np.square(mat1)

array([[4.44016278e-03, 5.82115234e+00, 1.05226110e-01],
       [3.76510755e-05, 3.48703984e-01, 1.89117537e-01],
       [3.15942126e+00, 9.67500354e-02, 1.68993653e+00],
       [4.41811841e-02, 1.66068736e-01, 1.91704559e-02],
       [5.56282701e-01, 4.14887360e+00, 3.79919337e+00]])

In [ ]:
# mat1의 제곱근 구하기
np.sqrt(mat1) #nan = not a number

<ipython-input-126-5f34006462b6>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(mat1)


array([[       nan, 1.55328891, 0.56954872],
       [0.07833293,        nan,        nan],
       [1.3332202 ,        nan,        nan],
       [       nan,        nan, 0.37209866],
       [0.86362238,        nan, 1.39612032]])

In [ ]:
# linear algebra functions
vec = np.array([1,2,2])

# 1. norm
np.linalg.norm(vec)

# 2. eigenvalue
mat = np.array([[1,2],
                [3,4]])
np.linalg.eig(mat)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

### 2.2. Aggregation functions 

In [ ]:
mat2 = np.random.rand(3, 2)
mat2

array([[0.00850517, 0.753121  ],
       [0.59194156, 0.28735934],
       [0.67847283, 0.48963282]])

In [ ]:
# Summation
np.sum(mat2)
np.sum(mat2, axis=1)
np.sum(mat2, axis=0)

array([1.27891956, 1.53011317])

In [ ]:
# mean
np.mean(mat2, axis=1)

array([0.38081309, 0.43965045, 0.58405283])

In [ ]:
# std 표준편차
np.std(mat2)

0.2533734589830205

In [ ]:
# min, max
print(np.min(mat2, axis=1))
print(np.max(mat2, axis=0))

[0.00850517 0.28735934 0.48963282]
[0.67847283 0.753121  ]


In [ ]:
# 최소값이 있는 Index
np.argmin(mat2, axis=0)

array([0, 1])

In [ ]:
# 최대값이 있는 Index
np.argmax(mat2, axis=1)

array([1, 0, 0])

In [ ]:
mat2

array([[0.00850517, 0.753121  ],
       [0.59194156, 0.28735934],
       [0.67847283, 0.48963282]])

In [ ]:
# 그냥 정렬 (오름차순 정렬만 지원합니다)
np.sort(mat2, axis=0)
np.sort(mat2, axis=0)[::-1]

array([[0.67847283, 0.753121  ],
       [0.59194156, 0.48963282],
       [0.00850517, 0.28735934]])

In [ ]:
# index를 정렬
np.argsort(mat2 ,axis=0)

array([[0, 1],
       [1, 2],
       [2, 0]])

## 3. Performance Check

- Universal Function 기능을 통해 반복문을 사용한 것보다 훨씬 빠른 성능을 냅니다.


- 직접 실험을 통해 그 차이를 확인해보겠습니다.

In [ ]:
#np.random.seed(0) #random에 대한 실행결과를 고정

def reverse_num(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    
    return output

In [ ]:
# 1부터 100까지 범위에서 1000000개를 랜덤으로 뽑아서 array를 만듭니다.
big_array = np.random.randint(1, 100, 1000000)
big_array

array([26, 82,  3, ...,  2, 90, 99])

In [ ]:
%timeit reverse_num(big_array)

2.46 s ± 352 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit 1.0 / big_array

1.74 ms ± 304 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
